groups:
  - name: uptime
    rules:
      - alert: WebsiteDown
        expr: probe_success == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Website is down"
          description: "The website has been unreachable for 30s."
